version: '3.8'

services:
  backend-service:
    build: ./backend
    ports:
      - "5000:5000"

  frontend-service:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend-service
